# this is the version of docker compose
version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379" # didn't work w/o this line
  node-app:
    restart: unless-stopped  # this container will always restart 
    build: . # look for a Dockerfile in the current file
    ports:
      - "4001:8081"